"""Add user_audio_association table

Revision ID: 9b138dc88f7f
Revises: 3e0211f260db
Create Date: 2025-03-29 15:34:05.420520

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b138dc88f7f"
down_revision: str | None = "3e0211f260db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_audio_association",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("audio_file_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_file_id"], ["audio_files.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "audio_file_id"),
        sa.UniqueConstraint("user_id", "audio_file_id", name="uq_user_audio_pair"),
    )
    op.create_index(
        "ix_user_audio_audio_file_id",
        "user_audio_association",
        ["audio_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_audio_user_id", "user_audio_association", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_audio_user_id", table_name="user_audio_association")
    op.drop_index("ix_user_audio_audio_file_id", table_name="user_audio_association")
    op.drop_table("user_audio_association")
    # ### end Alembic commands ###
